-- MySQL Script generated by MySQL Workbench
-- sex 07 jun 2019 18:53:31 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome_categoria` VARCHAR(20) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `ISBN` INT NOT NULL,
  `titulo` VARCHAR(30) NULL,
  `anoLancamento` DATE NOT NULL,
  `autor` VARCHAR(20) NULL,
  `editora` VARCHAR(15) NULL,
  `coAutor` VARCHAR(20) NULL,
  `quantLivro` INT NULL,
  `categoria_idcategoria` INT UNSIGNED NOT NULL,
  `dia_emprestimo` DATE NULL,
  `dia_entrega` DATE NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC),
  INDEX `fk_livro_categoria_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_livro_categoria`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(20) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `cod_Curso` INT NOT NULL,
  `nomeCurso` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_Curso`),
  UNIQUE INDEX `cod_Curso_UNIQUE` (`cod_Curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(20) NULL,
  `endereco` VARCHAR(15) NULL,
  `id_Curso` VARCHAR(45) NULL,
  `data_Entrada` DATE NULL,
  `data_Saida` DATE NULL,
  `curso_cod_Curso` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_aluno_curso1_idx` (`curso_cod_Curso` ASC),
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`curso_cod_Curso`)
    REFERENCES `mydb`.`curso` (`cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro_has_autor` (
  `livro_ISBN` INT NOT NULL,
  `autor_CPF` INT NOT NULL,
  PRIMARY KEY (`livro_ISBN`, `autor_CPF`),
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_CPF` ASC),
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_ISBN` ASC),
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_ISBN`)
    REFERENCES `mydb`.`livro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_CPF`)
    REFERENCES `mydb`.`autor` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `mat_siap` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(15) NULL,
  `cod_Curso` INT NULL,
  `data_contratacao` DATE NULL,
  `cargaHora` INT NULL,
  PRIMARY KEY (`mat_siap`),
  UNIQUE INDEX `mat_siap_UNIQUE` (`mat_siap` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(20) NULL,
  `endereco` VARCHAR(15) NULL,
  `cargaHora` INT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_has_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor_has_curso` (
  `professor_mat_siap` INT NOT NULL,
  `curso_cod_Curso` INT NOT NULL,
  PRIMARY KEY (`professor_mat_siap`, `curso_cod_Curso`),
  INDEX `fk_professor_has_curso_curso1_idx` (`curso_cod_Curso` ASC),
  INDEX `fk_professor_has_curso_professor1_idx` (`professor_mat_siap` ASC),
  CONSTRAINT `fk_professor_has_curso_professor1`
    FOREIGN KEY (`professor_mat_siap`)
    REFERENCES `mydb`.`professor` (`mat_siap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_curso_curso1`
    FOREIGN KEY (`curso_cod_Curso`)
    REFERENCES `mydb`.`curso` (`cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor_has_livro` (
  `professor_mat_siap` INT NOT NULL,
  `livro_ISBN` INT NOT NULL,
  PRIMARY KEY (`professor_mat_siap`, `livro_ISBN`),
  INDEX `fk_professor_has_livro_livro1_idx` (`livro_ISBN` ASC),
  INDEX `fk_professor_has_livro_professor1_idx` (`professor_mat_siap` ASC),
  CONSTRAINT `fk_professor_has_livro_professor1`
    FOREIGN KEY (`professor_mat_siap`)
    REFERENCES `mydb`.`professor` (`mat_siap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_livro_livro1`
    FOREIGN KEY (`livro_ISBN`)
    REFERENCES `mydb`.`livro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_has_livro` (
  `aluno_matricula` INT NOT NULL,
  `livro_ISBN` INT NOT NULL,
  PRIMARY KEY (`aluno_matricula`, `livro_ISBN`),
  INDEX `fk_aluno_has_livro_livro1_idx` (`livro_ISBN` ASC),
  INDEX `fk_aluno_has_livro_aluno1_idx` (`aluno_matricula` ASC),
  CONSTRAINT `fk_aluno_has_livro_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_livro_livro1`
    FOREIGN KEY (`livro_ISBN`)
    REFERENCES `mydb`.`livro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario_has_livro` (
  `funcionario_matricula` INT NOT NULL,
  `livro_ISBN` INT NOT NULL,
  PRIMARY KEY (`funcionario_matricula`, `livro_ISBN`),
  INDEX `fk_funcionario_has_livro_livro1_idx` (`livro_ISBN` ASC),
  INDEX `fk_funcionario_has_livro_funcionario1_idx` (`funcionario_matricula` ASC),
  CONSTRAINT `fk_funcionario_has_livro_funcionario1`
    FOREIGN KEY (`funcionario_matricula`)
    REFERENCES `mydb`.`funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_livro_livro1`
    FOREIGN KEY (`livro_ISBN`)
    REFERENCES `mydb`.`livro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`vw_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vw_professores` (`professor` INT, `livro` INT, `categoria` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`vw_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vw_curso` (`categoria` INT, `editora` INT, `titulo` INT);

-- -----------------------------------------------------
-- View `mydb`.`vw_professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vw_professores`;
USE `mydb`;
CREATE  OR REPLACE VIEW `vw_professores` AS 
SELECT professor.nome AS professor, livro.titulo AS livro, categoria.nome_categoria AS categoria
FROM cateforia, livro, professor
ORDER BY professor;

-- -----------------------------------------------------
-- View `mydb`.`vw_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vw_curso`;
USE `mydb`;
CREATE  OR REPLACE VIEW `vw_curso` AS
SELECT categoria.nome_categoria AS categoria,
       livro.editora AS editora,
       livro.titulo AS titulo
FROM livro INNER JOIN categoria ON livro.categoria_idcategoria = categoria.idcategoria;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
